#!/usr/bin/env bash
# Installs snipux for the current user: a self-contained virtual environment,
# the package itself, a launcher on PATH, then the .desktop file so it shows
# up in GNOME's application list.
#
# User-local throughout -- no sudo, nothing under /usr/share, and nothing
# written into the system Python's site-packages. Ubuntu 23.04+ (including
# 24.04 LTS, the likely target) marks that site-packages externally managed
# under PEP 668, so a bare `pip install` there aborts with
# "externally-managed-environment"; the fix is a venv of our own, not
# --break-system-packages.

# Platform check first, before any other command runs: a failed step further
# down must not be what a non-Linux user sees, this must be the first thing
# that runs.
if [ "$(uname -s)" != "Linux" ]; then
    echo "error: snipux only installs on Linux (found: $(uname -s))" >&2
    exit 1
fi

set -e

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

# $XDG_DATA_HOME if the user has set it, ~/.local/share otherwise. The venv
# lives under here -- not under the repo checkout -- so it survives
# `git clean` and doesn't depend on this checkout staying where it is.
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
venv_dir="$data_home/snipux/venv"
bin_dir="$HOME/.local/bin"
launcher="$bin_dir/snipux"

# `python3 -m venv` needs the venv stdlib module, which Debian/Ubuntu ship as
# a separate package from the interpreter itself (absent on a fresh image
# until it's installed). Name that package rather than let the user decode
# venv's own traceback.
if ! python3 -m venv --help >/dev/null 2>&1; then
    echo "error: the python3 venv module is not available." >&2
    echo "Install it with: sudo apt install python3-venv" >&2
    exit 1
fi

# Safe to re-run: rebuild the venv from scratch rather than installing over
# whatever is already there, so a stale or half-finished environment from a
# previous run never lingers into this one.
echo "Creating virtual environment in $venv_dir..."
rm -rf "$venv_dir"
python3 -m venv "$venv_dir"

# The venv's own pip, never the system one -- this is what keeps snipux and
# its dependencies out of the distribution's site-packages, no
# --break-system-packages needed. Runtime dependencies come from
# pyproject.toml's own [project] metadata.
echo "Installing snipux and its runtime dependencies..."
"$venv_dir/bin/python" -m pip install --quiet --upgrade pip
"$venv_dir/bin/python" -m pip install "$repo_root"

# A thin launcher on PATH rather than pointing PATH at the venv's bin/
# directly -- that would also expose the venv's own python/pip, shadowing
# the system ones in every shell that picked it up.
echo "Installing launcher into $bin_dir..."
mkdir -p "$bin_dir"
cat > "$launcher" <<LAUNCHER
#!/usr/bin/env bash
# Generated by packaging/install.sh. Runs snipux from its own virtual
# environment so the system Python is never touched; re-run install.sh to
# regenerate this file after moving or reinstalling snipux.
exec "$venv_dir/bin/snipux" "\$@"
LAUNCHER
chmod +x "$launcher"

applications_dir="$HOME/.local/share/applications"
echo "Installing desktop entry into $applications_dir..."
mkdir -p "$applications_dir"
cp "$script_dir/snipux.desktop" "$applications_dir/snipux.desktop"

# The launcher goes into ~/.local/bin -- whether that's on PATH for a
# *graphical* GNOME session (as opposed to the login shell this script runs
# under) depends on how the display manager builds the session environment.
# Check rather than assume, so a broken PATH shows up here instead of as a
# silently dead tray icon / Super+Shift+S binding later.
if command -v snipux >/dev/null 2>&1; then
    echo "Done. snipux is on PATH and listed in GNOME's application list."
else
    echo "Done. snipux is installed and listed in GNOME's application list,"
    echo "but $bin_dir is not on PATH in this shell (checked: command -v snipux)."
    echo "The .desktop entry's Exec=snipux line and the Super+Shift+S binding"
    echo "both need it resolvable in a graphical session too -- make sure"
    echo "$bin_dir is on PATH there, e.g. by logging out and back in."
fi
echo "Next: bind Super+Shift+S to it -- see docs/super-shift-s-gnome.md."
