#!/usr/bin/env bash
# Installs snipux for the current user: a self-contained virtual environment,
# the package itself, a launcher on PATH, then the .desktop file so it shows
# up in GNOME's application list.
#
# User-local throughout -- no sudo, nothing under /usr/share, and nothing
# written into the system Python's site-packages. Ubuntu 23.04+ (including
# 24.04 LTS, the likely target) marks that site-packages externally managed
# under PEP 668, so a bare `pip install` there aborts with
# "externally-managed-environment"; the fix is a venv of our own, not
# --break-system-packages.

# Platform check first, before any other command runs: a failed step further
# down must not be what a non-Linux user sees, this must be the first thing
# that runs.
if [ "$(uname -s)" != "Linux" ]; then
    echo "error: snipux only installs on Linux (found: $(uname -s))" >&2
    exit 1
fi

set -e

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

# $XDG_DATA_HOME if the user has set it, ~/.local/share otherwise. The venv
# lives under here -- not under the repo checkout -- so it survives
# `git clean` and doesn't depend on this checkout staying where it is.
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
venv_dir="$data_home/snipux/venv"
bin_dir="$HOME/.local/bin"
launcher="$bin_dir/snipux"

# `python3 -m venv` needs the venv stdlib module, which Debian/Ubuntu ship as
# a separate package from the interpreter itself (absent on a fresh image
# until it's installed). Name that package rather than let the user decode
# venv's own traceback.
if ! python3 -m venv --help >/dev/null 2>&1; then
    echo "error: the python3 venv module is not available." >&2
    echo "Install it with: sudo apt install python3-venv" >&2
    exit 1
fi

# Safe to re-run: rebuild the venv from scratch rather than installing over
# whatever is already there, so a stale or half-finished environment from a
# previous run never lingers into this one.
echo "Creating virtual environment in $venv_dir..."
rm -rf "$venv_dir"
python3 -m venv "$venv_dir"

# The venv's own pip, never the system one -- this is what keeps snipux and
# its dependencies out of the distribution's site-packages, no
# --break-system-packages needed. Runtime dependencies come from
# pyproject.toml's own [project] metadata.
echo "Installing snipux and its runtime dependencies..."
"$venv_dir/bin/python" -m pip install --quiet --upgrade pip
"$venv_dir/bin/python" -m pip install "$repo_root"

# A thin launcher on PATH rather than pointing PATH at the venv's bin/
# directly -- that would also expose the venv's own python/pip, shadowing
# the system ones in every shell that picked it up.
echo "Installing launcher into $bin_dir..."
mkdir -p "$bin_dir"
cat > "$launcher" <<LAUNCHER
#!/usr/bin/env bash
# Generated by packaging/install.sh. Runs snipux from its own virtual
# environment so the system Python is never touched; re-run install.sh to
# regenerate this file after moving or reinstalling snipux.
exec "$venv_dir/bin/snipux" "\$@"
LAUNCHER
chmod +x "$launcher"

# The .desktop file in the repo carries a placeholder Exec= line rather than
# a bare "snipux" -- $bin_dir is not reliably on PATH in a graphical GNOME
# session (see the keybinding below, which hit this same issue), so the
# entries that get installed must carry the launcher's absolute path
# instead of a name that may not resolve. `sed` (not `cp`) writes the real
# path in on every run, so re-running this script rewrites both entries
# rather than leaving a stale path behind.
applications_dir="$HOME/.local/share/applications"
echo "Installing desktop entry into $applications_dir..."
mkdir -p "$applications_dir"
sed "s|^Exec=__SNIPUX_LAUNCHER__$|Exec=$launcher|" "$script_dir/snipux.desktop" > "$applications_dir/snipux.desktop"
echo "Desktop entry written to $applications_dir/snipux.desktop (Exec=$launcher)"

# Same .desktop file, second copy in the XDG autostart directory -- that is
# the only difference between "launchable from the applications list" and
# "brought back automatically at login" under the freedesktop autostart
# spec, which GNOME (and every other compliant desktop) honours by reading
# ~/.config/autostart/*.desktop at session start. Writing (not copying) is
# already idempotent: re-running this just overwrites the same filename,
# never adds a second entry.
autostart_dir="${XDG_CONFIG_HOME:-$HOME/.config}/autostart"
echo "Installing autostart entry into $autostart_dir..."
mkdir -p "$autostart_dir"
sed "s|^Exec=__SNIPUX_LAUNCHER__$|Exec=$launcher|" "$script_dir/snipux.desktop" > "$autostart_dir/snipux.desktop"
echo "Autostart entry written to $autostart_dir/snipux.desktop (Exec=$launcher)"

# The launcher goes into ~/.local/bin -- whether that's on PATH for a
# *graphical* GNOME session (as opposed to the login shell this script runs
# under) depends on how the display manager builds the session environment.
# Check rather than assume, so a broken PATH shows up here instead of as a
# silently dead terminal invocation later. The .desktop entries above are
# unaffected either way, since they now carry $launcher's absolute path
# rather than the bare "snipux" name.
if command -v snipux >/dev/null 2>&1; then
    echo "Done. snipux is on PATH and listed in GNOME's application list."
else
    echo "Done. snipux is installed and listed in GNOME's application list,"
    echo "but $bin_dir is not on PATH in this shell (checked: command -v snipux)."
    echo "Typing plain \"snipux\" from a terminal won't work there -- use"
    echo "$launcher, or add $bin_dir to PATH, e.g. by logging out and back in."
fi

# Bind Super+Shift+S to the launcher via GNOME's custom-keybindings
# mechanism -- see docs/super-shift-s-gnome.md for what this does by hand
# and how to undo it. The launcher's absolute path is used (not the bare
# "snipux" name) because $bin_dir is not reliably on PATH in a graphical
# GNOME session, as just checked above.
media_keys_schema="org.gnome.settings-daemon.plugins.media-keys"
slot_path="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/snipux/"
slot_schema="$media_keys_schema.custom-keybinding:$slot_path"
shortcut_bound=false

if ! command -v gsettings >/dev/null 2>&1; then
    echo "Note: gsettings not found -- cannot bind Super+Shift+S automatically."
    echo "See docs/super-shift-s-gnome.md to bind it by hand."
elif ! current_keybindings="$(gsettings get "$media_keys_schema" custom-keybindings 2>/dev/null)"; then
    echo "Note: could not read GNOME's custom-keybindings list -- cannot bind"
    echo "Super+Shift+S automatically. See docs/super-shift-s-gnome.md to bind it by hand."
else
    case "$current_keybindings" in
        *"'$slot_path'"*)
            # A previous run of this script already appended our slot --
            # reuse it instead of adding a duplicate entry.
            ;;
        "@as []")
            current_keybindings="['$slot_path']"
            ;;
        *)
            # Splice our slot into the existing list rather than replacing
            # it, so shortcuts the user set up by hand are kept.
            current_keybindings="${current_keybindings%]}, '$slot_path']"
            ;;
    esac

    if gsettings set "$media_keys_schema" custom-keybindings "$current_keybindings" \
        && gsettings set "$slot_schema" name 'snipux' \
        && gsettings set "$slot_schema" command "$launcher --snip" \
        && gsettings set "$slot_schema" binding '<Super><Shift>s'
    then
        shortcut_bound=true
    else
        echo "Note: setting the GNOME shortcut failed -- cannot bind Super+Shift+S"
        echo "automatically. See docs/super-shift-s-gnome.md to bind it by hand."
    fi
fi

if [ "$shortcut_bound" = true ]; then
    echo "Bound Super+Shift+S to run: $launcher --snip"
fi

# Start snipux now, rather than leaving the user to wait for the next login
# for the autostart entry above to fire -- otherwise the keybinding just
# bound would silently do nothing until a reboot.
#
# A bare launch (no --snip) is the resident/tray entry point
# (run_resident_app() in snipux/app.py); if nothing is listening on its
# single-instance socket yet it becomes the resident instance, and if
# something already is, it forwards a snip request to it instead of
# refusing to start. That forwarding is exactly right for the keybinding,
# but not here: re-running this script with snipux already running must
# leave it alone, not pop open the capture overlay as a side effect of
# checking. So the running-or-not check happens here, in the shell, before
# the launcher is invoked at all.
if [ -z "${DISPLAY:-}" ] && [ -z "${WAYLAND_DISPLAY:-}" ]; then
    echo "Could not start snipux: no graphical session detected (neither"
    echo "DISPLAY nor WAYLAND_DISPLAY is set). It will start automatically"
    echo "at your next graphical login via the autostart entry above."
elif command -v pgrep >/dev/null 2>&1 && pgrep -f "$venv_dir/bin/snipux" >/dev/null 2>&1; then
    echo "snipux is already running."
else
    echo "Starting snipux..."
    nohup "$launcher" >/dev/null 2>&1 </dev/null &
    disown
    echo "Started snipux (pid $!)."
fi
