#!/usr/bin/env bash
# Installs snipux for the current user: a self-contained virtual environment,
# the package itself, a launcher on PATH, then `snipux --setup` (SNX-73) for
# the desktop entry, autostart entry, and GNOME shortcut so it shows up in
# GNOME's application list and Super+Shift+S works.
#
# User-local throughout -- no sudo, nothing under /usr/share, and nothing
# written into the system Python's site-packages. Ubuntu 23.04+ (including
# 24.04 LTS, the likely target) marks that site-packages externally managed
# under PEP 668, so a bare `pip install` there aborts with
# "externally-managed-environment"; the fix is a venv of our own, not
# --break-system-packages.

# Platform check first, before any other command runs: a failed step further
# down must not be what a non-Linux user sees, this must be the first thing
# that runs.
if [ "$(uname -s)" != "Linux" ]; then
    echo "error: snipux only installs on Linux (found: $(uname -s))" >&2
    exit 1
fi

set -e

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

# $XDG_DATA_HOME if the user has set it, ~/.local/share otherwise. The venv
# lives under here -- not under the repo checkout -- so it survives
# `git clean` and doesn't depend on this checkout staying where it is.
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
venv_dir="$data_home/snipux/venv"
bin_dir="$HOME/.local/bin"
launcher="$bin_dir/snipux"

# `python3 -m venv` needs the venv stdlib module, which Debian/Ubuntu ship as
# a separate package from the interpreter itself (absent on a fresh image
# until it's installed). Name that package rather than let the user decode
# venv's own traceback.
if ! python3 -m venv --help >/dev/null 2>&1; then
    echo "error: the python3 venv module is not available." >&2
    echo "Install it with: sudo apt install python3-venv" >&2
    exit 1
fi

# Same reasoning as the venv check above, for a dependency that is not
# Python's at all: from Qt 6.5 the xcb platform plugin links libxcb-cursor,
# which Ubuntu does not pull in for anything else, so a stock desktop has
# every other Qt dependency and not this one. Checked here rather than left
# to runtime because the failure is a SIGABRT behind four lines of Qt plugin
# text ("Could not load the Qt platform plugin \"xcb\" ... even though it was
# found") that names the library but not the package to install -- and this
# script's own last act is starting snipux, so without this the install
# "succeeds" and then core-dumps.
#
# ldconfig, not dpkg: the library is what Qt actually dlopen()s, and asking
# the linker cache keeps this working where the same library arrives under a
# different package name.
if ! ldconfig -p 2>/dev/null | grep -q 'libxcb-cursor\.so\.0'; then
    echo "error: libxcb-cursor.so.0 is not installed." >&2
    echo "Qt 6.5+ needs it to load its xcb platform plugin; without it" >&2
    echo "snipux installs but crashes on launch." >&2
    echo "Install it with: sudo apt install libxcb-cursor0" >&2
    exit 1
fi

# Safe to re-run: rebuild the venv from scratch rather than installing over
# whatever is already there, so a stale or half-finished environment from a
# previous run never lingers into this one.
echo "Creating virtual environment in $venv_dir..."
rm -rf "$venv_dir"
python3 -m venv "$venv_dir"

# The venv's own pip, never the system one -- this is what keeps snipux and
# its dependencies out of the distribution's site-packages, no
# --break-system-packages needed. Runtime dependencies come from
# pyproject.toml's own [project] metadata.
echo "Installing snipux and its runtime dependencies..."
"$venv_dir/bin/python" -m pip install --quiet --upgrade pip
"$venv_dir/bin/python" -m pip install "$repo_root"

# A thin launcher on PATH rather than pointing PATH at the venv's bin/
# directly -- that would also expose the venv's own python/pip, shadowing
# the system ones in every shell that picked it up.
echo "Installing launcher into $bin_dir..."
mkdir -p "$bin_dir"
cat > "$launcher" <<LAUNCHER
#!/usr/bin/env bash
# Generated by packaging/install.sh. Runs snipux from its own virtual
# environment so the system Python is never touched; re-run install.sh to
# regenerate this file after moving or reinstalling snipux.
exec "$venv_dir/bin/snipux" "\$@"
LAUNCHER
chmod +x "$launcher"

# Desktop entry, autostart entry, and the GNOME Super+Shift+S shortcut are
# all `snipux --setup`'s job (SNX-73) -- it ships its own .desktop template
# inside the package and writes it under both locations, plus the
# gsettings dance below the keybinding used to be. Delegating here rather
# than repeating that logic in shell is the whole point: one
# implementation, not two that drift. `$launcher` is used (not a bare
# "snipux") so this works even before $bin_dir is confirmed to be on PATH,
# just like every other launcher invocation below.
echo "Running snipux --setup..."
"$launcher" --setup

# The launcher goes into ~/.local/bin -- whether that's on PATH for a
# *graphical* GNOME session (as opposed to the login shell this script runs
# under) depends on how the display manager builds the session environment.
# Check rather than assume, so a broken PATH shows up here instead of as a
# silently dead terminal invocation later. The .desktop entries `--setup`
# just wrote are unaffected either way, since they carry the venv's console
# script's own absolute path rather than the bare "snipux" name.
if command -v snipux >/dev/null 2>&1; then
    echo "Done. snipux is on PATH and listed in GNOME's application list."
else
    echo "Done. snipux is installed and listed in GNOME's application list,"
    echo "but $bin_dir is not on PATH in this shell (checked: command -v snipux)."
    echo "Typing plain \"snipux\" from a terminal won't work there -- use"
    echo "$launcher, or add $bin_dir to PATH, e.g. by logging out and back in."
fi

# Start snipux now, rather than leaving the user to wait for the next login
# for the autostart entry above to fire -- otherwise the keybinding just
# bound would silently do nothing until a reboot.
#
# A bare launch (no --snip) is the resident/tray entry point
# (run_resident_app() in snipux/app.py); if nothing is listening on its
# single-instance socket yet it becomes the resident instance, and if
# something already is, it forwards a snip request to it instead of
# refusing to start. That forwarding is exactly right for the keybinding,
# but not here: re-running this script with snipux already running must
# leave it alone, not pop open the capture overlay as a side effect of
# checking. So the running-or-not check happens here, in the shell, before
# the launcher is invoked at all.
if [ -z "${DISPLAY:-}" ] && [ -z "${WAYLAND_DISPLAY:-}" ]; then
    echo "Could not start snipux: no graphical session detected (neither"
    echo "DISPLAY nor WAYLAND_DISPLAY is set). It will start automatically"
    echo "at your next graphical login via the autostart entry above."
elif command -v pgrep >/dev/null 2>&1 && pgrep -f "$venv_dir/bin/snipux" >/dev/null 2>&1; then
    echo "snipux is already running."
else
    echo "Starting snipux..."
    nohup "$launcher" >/dev/null 2>&1 </dev/null &
    disown
    echo "Started snipux (pid $!)."
fi
